apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weshopify-app-db-deployment
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: weshopify-app-db
  template: 
    metadata: 
      labels: 
        app: weshopify-app-db
    spec: 
      volumes: 
        - name: weshopify-app-db-volume
          persistentVolumeClaim: 
            claimName: weshopify-db-pvc
      containers: 
        - name: weshopify-app-db
          image: mysql
          ports: 
            - containerPort: 3306
          volumeMounts:
            - name: weshopify-app-db-volume
              mountPath: /opt/mysql
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: weshopify-db-config-secret
                  key: DB_PASSWORD_VALUE
            - name: MYSQL_DATABASE
              valueFrom: 
                configMapKeyRef: 
                  name: weshopify-db-config-map
                  key: DB_SCHEMA_VALUE
            - name: MYSQL_USER
              valueFrom: 
                secretKeyRef: 
                  name: weshopify-db-config-secret
                  key: DB_USER_NAME_VALUE
            - name: MYSQL_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: weshopify-db-config-secret
                  key: DB_PASSWORD_VALUE
---
apiVersion: v1
kind: Service
metadata: 
  name: weshopify-app-db-service
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector: 
    app: weshopify-app-db
