apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-mysql
  template:
    metadata:
      labels:
        app: spring-boot-mysql
    spec:
      containers:
        - name: spring-boot-mysql
          image: ashokit/spring-boot-mysql
          ports:
            - containerPort: 8080
          env:   
            - name: DB_DRIVER_CLASS
              valueFrom:
                configMapKeyRef:
                  name: weshopify-db-config-map
                  key: DB_DRIVER_NAME_VALUE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: weshopify-db-config-map
                  key: DB_HOST_SERVICE_NAME_VALUE
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: weshopify-db-config-map
                  key: DB_SCHEMA_VALUE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: weshopify-db-config-secret
                  key: DB_USER_NAME_VALUE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weshopify-db-config-secret
                  key: DB_PASSWORD_VALUE

---
apiVersion: v1
kind: Service
metadata: 
  name: springboot-mysql-svc
spec:
  selector:
    app: spring-boot-mysql
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
