---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: weatherapprs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nguti-app
  template:
    metadata:
      name: weatherapppod
      labels:
        app: nguti-app
    spec: 
      containers:
      - name: javawebappcontainer
        image: ekangaki/weather-app:latest
        ports: 
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weatherappsvc
spec:
  type: NodePort
  selector:
    app: nguti-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30785
...
