---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      name: springboot-app
      labels:
        app: springboot-app
    spec: 
      containers:
      - name: springboot-app-container
        image: ashokit/sb-logger-app
        ports: 
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - port: 80
      targetPort: 8080
...
